import express from 'express';
import cors from 'cors';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import PDFDocument from 'pdfkit';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DATA_FILE = path.join(__dirname, 'data', 'notes.json');

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

// Helper: Read notes
async function readNotes() {
  try {
    const data = await fs.readFile(DATA_FILE, 'utf-8');
    return JSON.parse(data);
  } catch (err) {
    console.error('Error reading notes.json:', err);
    return [];
  }
}

// Helper: Write notes
async function writeNotes(notes) {
  try {
    await fs.writeFile(DATA_FILE, JSON.stringify(notes, null, 2), 'utf-8');
  } catch (err) {
    console.error('Error writing notes.json:', err);
    throw err;
  }
}

function sanitizeFilename(title) {
  return (title || 'note').replace(/[^a-zA-Z0-9_-]/g, '_').substring(0, 50);
}

// Helper: Generate PDF stream with PDFKit
function generatePdfStream(note, res, disposition = 'attachment') {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  const safeTitle = sanitizeFilename(note.title);
  const filename = `${safeTitle}.pdf`;

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `${disposition}; filename="${filename}"`);

  doc.pipe(res);

  // PDF Header Banner
  doc.rect(50, 40, 500, 30).fill('#0066cc');
  doc.fillColor('#ffffff').fontSize(12).font('Helvetica-Bold')
     .text('STUDY NOTES PORTAL  •  ACADEMIC REFERENCE', 60, 50);

  doc.moveDown(2);

  // Note Title
  doc.fillColor('#1a1a1a').fontSize(20).font('Helvetica-Bold')
     .text(note.title, 50, 90);

  // Metadata Row
  doc.moveDown(0.5);
  doc.fontSize(11).font('Helvetica')
     .fillColor('#555555')
     .text(`Subject: ${note.subject || note.category || 'General'}    |    Semester: ${note.semester || '3rd Sem'}    |    Date: ${note.createdAt || '2026'}`);

  if (note.topics && note.topics.length > 0) {
    doc.moveDown(0.4);
    doc.fontSize(10).font('Helvetica-Oblique').fillColor('#0066cc')
       .text(`Key Topics: ${note.topics.join('  •  ')}`);
  }

  // Divider Line
  doc.moveDown(0.8);
  const yLine = doc.y;
  doc.strokeColor('#cccccc').lineWidth(1)
     .moveTo(50, yLine).lineTo(550, yLine).stroke();

  doc.moveDown(1.2);

  // Note Content Body
  doc.fontSize(11).font('Helvetica').fillColor('#222222').lineGap(4);

  const paragraphs = (note.content || '').split('\n');
  paragraphs.forEach(p => {
    if (p.startsWith('CHAPTER') || p.startsWith('Unit') || p.endsWith(':')) {
      doc.moveDown(0.5);
      doc.font('Helvetica-Bold').fillColor('#004499').fontSize(13).text(p);
      doc.font('Helvetica').fillColor('#222222').fontSize(11);
    } else {
      doc.text(p);
    }
  });

  // Footer on bottom of page
  doc.fontSize(9).fillColor('#888888')
     .text('Generated by Notes App • Search and Download Portal', 50, 780, { align: 'center', width: 500 });

  doc.end();
}

// ==========================================
// REST API Routes
// ==========================================

// 1. GET /api/notes - Search & list PDF notes
app.get('/api/notes', async (req, res) => {
  try {
    const { search, category } = req.query;
    let notes = await readNotes();

    // Category / Subject filter
    if (category && category.toLowerCase() !== 'all') {
      notes = notes.filter(n => (n.subject || n.category || '').toLowerCase() === category.toLowerCase());
    }

    // Search query filter
    if (search && search.trim()) {
      const q = search.trim().toLowerCase();
      notes = notes.filter(n => {
        const title = (n.title || '').toLowerCase();
        const content = (n.content || '').toLowerCase();
        const subject = (n.subject || n.category || '').toLowerCase();
        const topics = (n.topics || []).join(' ').toLowerCase();

        return title.includes(q) || content.includes(q) || subject.includes(q) || topics.includes(q);
      });
    }

    res.json({
      success: true,
      count: notes.length,
      notes
    });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to fetch notes' });
  }
});

// 2. GET /api/notes/:id/download - Download Note as PDF
app.get('/api/notes/:id/download', async (req, res) => {
  try {
    const notes = await readNotes();
    const note = notes.find(n => n.id === req.params.id);

    if (!note) {
      return res.status(404).send('Note not found');
    }

    // Increment download count
    note.downloads = (note.downloads || 0) + 1;
    await writeNotes(notes);

    // Stream PDF as attachment download
    generatePdfStream(note, res, 'attachment');
  } catch (error) {
    console.error('PDF download error:', error);
    res.status(500).send('Failed to generate PDF');
  }
});

// 3. GET /api/notes/:id/view - View/Preview PDF directly in browser
app.get('/api/notes/:id/view', async (req, res) => {
  try {
    const notes = await readNotes();
    const note = notes.find(n => n.id === req.params.id);

    if (!note) {
      return res.status(404).send('Note not found');
    }

    // Stream PDF inline
    generatePdfStream(note, res, 'inline');
  } catch (error) {
    console.error('PDF view error:', error);
    res.status(500).send('Failed to display PDF');
  }
});

// 4. POST /api/notes - Add new PDF note
app.post('/api/notes', async (req, res) => {
  try {
    const { title, subject, category, topics, content } = req.body;

    if (!title || !content) {
      return res.status(400).json({ success: false, message: 'Title and content are required' });
    }

    const notes = await readNotes();

    const topicList = Array.isArray(topics)
      ? topics
      : (typeof topics === 'string' ? topics.split(',').map(t => t.trim()).filter(Boolean) : []);

    const newNote = {
      id: `pdf-${Date.now()}`,
      title: title.trim(),
      subject: (subject || category || 'General').trim(),
      semester: '3rd Sem CS',
      pages: Math.max(1, Math.ceil(content.split('\n').length / 15)),
      fileSize: `${Math.max(50, Math.round(content.length / 10))} KB`,
      createdAt: new Date().toISOString().slice(0, 10),
      downloads: 0,
      topics: topicList,
      content: content.trim()
    };

    notes.unshift(newNote);
    await writeNotes(notes);

    res.status(201).json({ success: true, note: newNote });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to create note' });
  }
});

// 5. DELETE /api/notes/:id - Delete a note
app.delete('/api/notes/:id', async (req, res) => {
  try {
    let notes = await readNotes();
    notes = notes.filter(n => n.id !== req.params.id);
    await writeNotes(notes);
    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Failed to delete note' });
  }
});

app.listen(PORT, () => {
  console.log(`🚀 PDF Notes Server running at http://localhost:${PORT}`);
});
