services:
  - type: web
    name: mzk-portfolio-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NOTIFICATION_EMAIL
        value: zaidkhan24082006@gmail.com
      - key: EMAIL_TO
        value: zaidkhan24082006@gmail.com
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: ADMIN_INITIAL_PASSWORD
        sync: false
      - key: GITHUB_TOKEN
        sync: false
